language: java
script: 
  - mvn clean install nbm:autoupdate
  - cd target/netbeans_site && zip -r nbscala-plugins.zip *.nbm
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "/home/travis/build/akochnev/nbscala/target/netbeans_site/nbscala-plugins.zip"
  skip_cleanup: true
  on:
    tags: true
